spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bookstoreapi_purchases
    password: a
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: purchases-api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost